spring:
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 8
    url: "jdbc:postgresql://localhost:11088/banzaidb"
    username: "user"
    password: "pass"
    driverClassName: "org.postgresql.Driver"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

scheduler:
  #Amount of threads in a ThreadPool
  workerThreads: 4
  #Amount of active producers at a time
  producers: 2
  #BlockingQueue size between producers and consumers
  queueBound: 10
  #Call rate between each folder scan in milliseconds
  pollingFrequency: 100
  #Folders to scan, place processed and unprocessed/broken files
  directory:
    source: "${user.home}/BanzaiFolder/New"
    processed: "${user.home}/BanzaiFolder/Old"
    error: "${user.home}/BanzaiFolder/Error"

