spring:
  datasource:
    url: "jdbc:postgresql://localhost:11088/banzaidb"
    username: "user"
    password: "pass"
    driverClassName: "org.postgresql.Driver"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

scheduler:
  workerThreads: 4
  producers: 2
  queueBound: 10
  pollingFrequency: 2000
  directory:
    source: "/Users/d.diallo/BanzaiFolder/New"
    processed: "/Users/d.diallo/BanzaiFolder/Old"
    error: "/Users/d.diallo/BanzaiFolder/Error"

